[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sulfin-binary-converter"
version = "0.0.1"
authors = [
    { name="sulfin", email="sulfin83@gmail.com" },
]
description = "A bi-directional binary decimal converter"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
