[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "example_package_PERRIN_Liam"
version = "0.0.2"
authors = [
  { name="PERRIN_Liam", email="liam.perrin@isen.yncrea.fr" },
]
description = "Test du deploiement"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Sletty4/M1-2022-git-workflow-PERRIN-Liam"
"Bug Tracker" = "https://github.com/Sletty4/M1-2022-git-workflow-PERRIN-Liam/issues"